<?php
//$Id$ 
//gen openMairie le 06/12/2010 10:59 
$reqmo['libelle']=' om_etat';
$reqmo['reqmo_libelle']=' om_etat';
$reqmo['sql']="select  [om_etat], [om_collectivite], [id], [libelle], [actif], [orientation], [format], [footerfont], [footerattribut], [footertaille], [logo], [logoleft], [logotop], [titre], [titreleft], [titretop], [titrelargeur], [titrehauteur], [titrefont], [titreattribut], [titretaille], [titrebordure], [titrealign], [corps], [corpsleft], [corpstop], [corpslargeur], [corpshauteur], [corpsfont], [corpsattribut], [corpstaille], [corpsbordure], [corpsalign], [om_sql], [sousetat], [se_font], [se_margeleft], [se_margetop], [se_margeright], [se_couleurtexte] from ".DB_PREFIXE."om_etat  order by [tri]";
$reqmo['om_etat']='checked';
$reqmo['om_collectivite']='checked';
$reqmo['id']='checked';
$reqmo['libelle']='checked';
$reqmo['actif']='checked';
$reqmo['orientation']='checked';
$reqmo['format']='checked';
$reqmo['footerfont']='checked';
$reqmo['footerattribut']='checked';
$reqmo['footertaille']='checked';
$reqmo['logo']='checked';
$reqmo['logoleft']='checked';
$reqmo['logotop']='checked';
$reqmo['titre']='checked';
$reqmo['titreleft']='checked';
$reqmo['titretop']='checked';
$reqmo['titrelargeur']='checked';
$reqmo['titrehauteur']='checked';
$reqmo['titrefont']='checked';
$reqmo['titreattribut']='checked';
$reqmo['titretaille']='checked';
$reqmo['titrebordure']='checked';
$reqmo['titrealign']='checked';
$reqmo['corps']='checked';
$reqmo['corpsleft']='checked';
$reqmo['corpstop']='checked';
$reqmo['corpslargeur']='checked';
$reqmo['corpshauteur']='checked';
$reqmo['corpsfont']='checked';
$reqmo['corpsattribut']='checked';
$reqmo['corpstaille']='checked';
$reqmo['corpsbordure']='checked';
$reqmo['corpsalign']='checked';
$reqmo['om_sql']='checked';
$reqmo['sousetat']='checked';
$reqmo['se_font']='checked';
$reqmo['se_margeleft']='checked';
$reqmo['se_margetop']='checked';
$reqmo['se_margeright']='checked';
$reqmo['se_couleurtexte']='checked';
$reqmo['tri']=array('om_etat','om_collectivite','id','libelle','actif','orientation','format','footerfont','footerattribut','footertaille','logo','logoleft','logotop','titre','titreleft','titretop','titrelargeur','titrehauteur','titrefont','titreattribut','titretaille','titrebordure','titrealign','corps','corpsleft','corpstop','corpslargeur','corpshauteur','corpsfont','corpsattribut','corpstaille','corpsbordure','corpsalign','om_sql','sousetat','se_font','se_margeleft','se_margetop','se_margeright','se_couleurtexte');
?>