<?php
//$Id$ 
//gen openMairie le 19/10/2010 18:45 
include('../gen/sql/mysql/om_lettretype.form.inc.php');
$champs=array("om_lettretype","om_collectivite","id","libelle",
              "actif","orientation","format",
              "logo","logoleft","logotop",
              "titre","titreleft","titretop",
              "titrelargeur","titrehauteur","titrefont",
              "titreattribut","titretaille","titrebordure",
              "titrealign",
              "corps","corpsleft","corpstop","corpslargeur",
              "corpshauteur","corpsfont","corpsattribut",
              "corpstaille","corpsbordure","corpsalign",
              "om_sql","'lettretype.png' as image");
// specifique
// "'lettretype.png' as image"); pour fct de localisation

?>