<?php
//$Id$ 
//gen openMairie le 06/12/2010 10:59 
$reqmo['libelle']=' om_lettretype';
$reqmo['reqmo_libelle']=' om_lettretype';
$reqmo['sql']="select  [om_lettretype], [om_collectivite], [id], [libelle], [actif], [orientation], [format], [logo], [logoleft], [logotop], [titre], [titreleft], [titretop], [titrelargeur], [titrehauteur], [titrefont], [titreattribut], [titretaille], [titrebordure], [titrealign], [corps], [corpsleft], [corpstop], [corpslargeur], [corpshauteur], [corpsfont], [corpsattribut], [corpstaille], [corpsbordure], [corpsalign], [om_sql] from ".DB_PREFIXE."om_lettretype  order by [tri]";
$reqmo['om_lettretype']='checked';
$reqmo['om_collectivite']='checked';
$reqmo['id']='checked';
$reqmo['libelle']='checked';
$reqmo['actif']='checked';
$reqmo['orientation']='checked';
$reqmo['format']='checked';
$reqmo['logo']='checked';
$reqmo['logoleft']='checked';
$reqmo['logotop']='checked';
$reqmo['titre']='checked';
$reqmo['titreleft']='checked';
$reqmo['titretop']='checked';
$reqmo['titrelargeur']='checked';
$reqmo['titrehauteur']='checked';
$reqmo['titrefont']='checked';
$reqmo['titreattribut']='checked';
$reqmo['titretaille']='checked';
$reqmo['titrebordure']='checked';
$reqmo['titrealign']='checked';
$reqmo['corps']='checked';
$reqmo['corpsleft']='checked';
$reqmo['corpstop']='checked';
$reqmo['corpslargeur']='checked';
$reqmo['corpshauteur']='checked';
$reqmo['corpsfont']='checked';
$reqmo['corpsattribut']='checked';
$reqmo['corpstaille']='checked';
$reqmo['corpsbordure']='checked';
$reqmo['corpsalign']='checked';
$reqmo['om_sql']='checked';
$reqmo['tri']=array('om_lettretype','om_collectivite','id','libelle','actif','orientation','format','logo','logoleft','logotop','titre','titreleft','titretop','titrelargeur','titrehauteur','titrefont','titreattribut','titretaille','titrebordure','titrealign','corps','corpsleft','corpstop','corpslargeur','corpshauteur','corpsfont','corpsattribut','corpstaille','corpsbordure','corpsalign','om_sql');
?>